### PR TITLE
Build with 7.10

### PR DESCRIPTION
**Pull request by olorin**
! @charleso @tmcgilchrist 

Have verified the published executable still works on both ancient (centos 6) and non-ancient (arch) linuxes. (There's a CLI test to check that the linking hack is still working, but I thought it best to make sure.)

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
:passenger_ship: 

Thanks for verifying manually.

**Comment by nhibberd** [comment]
Connection needs to be locked down to `0.2.5`

**Comment by olorin** [comment]
> Connection needs to be locked down to 0.2.5

Gah. Yes. Thanks for catching, will fix.

**Comment by charleso** [comment]
Apart from connection version 👍

**Comment by tmcgilchrist** [comment]
Why does `connection` need a specific version? @nhibberd

**Comment by olorin** [comment]
> Why does connection need a specific version? @nhibberd

Because of a buggy `http-client`/`connection` version combination which causes nondeterministic garbage-appearing-in-http-requests-on-the-wire. See https://github.com/erikd-ambiata/test-warp-wai/issues/1 for details.

**Pull request merged**
