### PR TITLE
Switch to mafia

### PR DESCRIPTION
**Pull request by jystic**
Build was failing because cabal has silly defaults:
```
# snip
Backjump limit reached (change with --max-backjumps).
```

Switch to mafia

### CODE REVIEW

**Comment by jystic** [comment]
It did fix the dependency resolution issue, but one of the tests seems to be failing?

**Comment by jystic** [comment]
```
Test suite test-cli: RUNNING...
Test suite test-cli: FAIL
Test suite logged to: dist/test/ambiata-cli-0.0.1-test-cli.log
2 of 3 test suites (2 of 3 test cases) passed.
*** Failed! Falsifiable (after 1 test): 
(ExitSuccess,True) /= (ExitSuccess,False)
```

**Comment by markhibberd** [comment]
@jystic Mmmmm, that is because static libgmp check is failing. @olorin maybe you could take a look tomorrow.

**Comment by markhibberd** [comment]
@jystic @olorin Mmm, actually, cabal extras had code to handle this in, it is actually probably missing from mafia. Will try to dig up link.

**Comment by markhibberd** [comment]
https://github.com/ambiata/ambiata-cli/blob/topic/mafia/bin/ci.common#L7 << this was picked up by cabal extras but isn't picked up by mafia.

**Comment by jystic** [comment]
@markhibberd cool, will look at adding flags to mafia tomorrow

**Comment by damncabbage** [comment]
Thank you both for looking at this. (This all started when I asked @jystic for help this evening with the failing Farm build in this PR: https://github.com/ambiata/manor/pull/124#issuecomment-176039346)

**Comment by jystic** [comment]
Hooray, it builds! Ok, one down, what do we do about this:
```
/mnt/tmp/hudson1591725890039118523.sh: line 2: bin/ci.farm: No such file or directory
```

**Comment by jystic** [comment]
Anyone know what `bin/ci.farm` is supposed to contain in the context of this project?

**Comment by charleso** [comment]
@jystic I've raised a PR to remove that build, I think it was added by mistake.

:+1:

**Pull request merged**
