### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by olorin**
Not sure who else belongs in `REVIEWERS` - @charleso maybe?

! @charleso @markhibberd

### CODE REVIEW

**Comment by charleso** [comment]
👍 

I'm happy to be added to `REVIEWERS`, but at the same time I would defer to Mark on anything non-trivial being done to this public-facing project.

**Comment by tmcgilchrist** [comment]
Is there an expectation that this needs to support more versions of GHC?
Do we upgrade it to 7.10 and 8, possibly dropping 7.8?

**Comment by olorin** [comment]
> Is there an expectation that this needs to support more versions of GHC?

Yes, I'm planning to bring it to 7.10 with the next PR - `zodiac`, `hadron` and `tinfoil` have dropped 7.8, so I'm not sure if they'd build anymore.

> Do we upgrade it to 7.10 and 8, possibly dropping 7.8?

I am planning to drop 7.8 and upgrade to 7.10, don't see any need to do 8.0 at this point though (don't really want to until we have 8.0 builds for all the deps).

**Comment by tmcgilchrist** [comment]
Carry on then. :+1:

**Comment by olorin** [comment]
@charleso 

> I'm happy to be added to REVIEWERS, but at the same time I would defer to Mark on anything non-trivial being done to this public-facing project.

Up to you. For me it's more of a "more eyes on the code" thing than an "approval to merge" thing, so it's a question of whether you know a bit about how some part of the code works (which I assume you do given the commit log) and whether or not you're interested.

**Pull request merged**
