### PR TITLE
Switch tatooine-cli over to use GET for upload rather than POST.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Requires changes to Aperture to support `GET /upload/s3`

### CODE REVIEW

**Comment by charleso** [comment]
Yeah, gonna need the changes to `aperture` to be rolled up to prod first

**Comment by tmcgilchrist** [comment]
Yes indeed, working on those now.

**Comment by markhibberd** [comment]
@charleso @tmcgilchrist can this be rebased/merged or closed?

**Comment by charleso** [comment]
Closing because aperture is still `POST` only.

**Pull request closed without merging**
